apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: cas-v2
type: Opaque
data:
  # echo -n admin | base64 | pbcopy
  user: YWRtaW4=
  # echo -n XVBYHTNw3Gg3TexQr5hb | base64 | pbcopy
  password: WFZCWUhUTnczR2czVGV4UXI1aGI=
  # echo -n casorder | base64 | pbcopy
  database: Y2Fzb3JkZXI=
