apiVersion: v1
kind: Secret
metadata:
  name: privatereg
  namespace: cas-v2
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWcuZnB0Y29tcHV0ZS5jb20udm4iOiB7CgkJCSJhdXRoIjogImEyaGhibWhqZERvNGEwMDFkVFoyUlRsclFWUlViMXBwIgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy4xNSAobGludXgpIgoJfQp9
