apiVersion: v1
kind: Service
metadata:
  name: cas-dashboard-lb
  namespace: cas-backup-v2
  labels:
    app: cas-dashboard-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.4.209
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: cas-dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas-dashboard
  namespace: cas-backup-v2
  labels:
    app: cas-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cas-dashboard
  template:
    metadata:
      labels:
        app: cas-dashboard
        node: cas-backup-v2
    spec:
      containers:
      - name: cas-dashboard
        image: reg.fptcompute.com.vn/cas-v2/casbackup-fe:0.1
        imagePullPolicy: Always
        ports:
        - name: cas-dashboard-p
          containerPort: 80
        resources:
          requests:
            memory: 500Mi
            cpu: 250m
          limits:
            memory: 2Gi
            cpu: 1000m
        volumeMounts:
        - name: casdb-cfg-vol
          mountPath: /etc/nginx/conf.d/
          readOnly: false
      imagePullSecrets:
      - name: privatereg
      volumes:
      - name: casdb-cfg-vol
        configMap:
          name: casdb-config
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cas-dashboard-scaler
  namespace: cas-backup-v2 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cas-dashboard
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: requests-per-second
        target:
          type: AverageValue
          averageValue: 1k